version: '3'
services:
  backend:
    build: ./backend
    environment: 
      # - NODE_ENV=production
      # - DEBUG=backend:*
      - NPM_CONFIG_LOGLEVEL=info
    ports:
      - '7000:7000'
    volumes:
      - ./backend:/home/node/backend
      - backend_node_mod:/home/node/backend/node_modules
    # command: npm run debug
    tty: true
    stdin_open: true
  
  db:
    image: postgres:10.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: stocker
      POSTGRES_USER: stocks
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db/data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'

  db-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=a@a.com
      - PGADMIN_DEFAULT_PASSWORD=123
    ports:
      - '5000:80'

volumes:
  backend_node_mod:
