version: '3'
services:
  backend:
    build: ./backend
    environment: 
      - NPM_CONFIG_PREFIX=/home/node/.npm-global
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=info
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/home/node/backend
      - backend_node_mod:/home/node/backend/node_modules
    tty: true
    stdin_open: true
volumes:
  backend_node_mod:
