version: '3'
services:
  backend:
    build: ./backend
    environment: 
      # - NODE_ENV=production
      - NPM_CONFIG_LOGLEVEL=info
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/home/node/backend
      - backend_node_mod:/home/node/backend/node_modules
    command: npm run debug
    tty: true
    stdin_open: true
volumes:
  backend_node_mod:
